### ISSUE TITLE
NASCOP VL/EID SYSTEM FAILURE

### ISSUE THREAD

**Issue by Liliankirigo96** [uon-crissp/IQVL#1]
For the last one week , the nascop website has failed to log in. We are unable to receive vl results for july.
Thus, unable to identify  clients with high VL

**Comment by LydiaKiragu** [comment]
Hi Lililan ,
As a gentle reminder,  we went over 2 links to access the same results. 

1. The Nascop site that we shared, that uses this link : https://eiddash.nascop.org/login.php (using the CASCO's credentials for username and pp for your county)

2. The second link being the KNH server accessed using this link and following these steps: 

http://knh.nascop.org:81/KNH/index.php

You will get to the landing page that looks like below. Click HERE for facility login.

![capture](https://user-images.githubusercontent.com/35918052/43764715-e458ae68-9a36-11e8-8804-1e87698ab51e.JPG)

From the select drop down - check for your facility and use the appropriate batch # as shown below. Which will take you to VL results by batch #s. You can either enter a filter by date range or choose a specific batch # to view the results needed. 


----

**Kirinyaga Facilities**

Facility | VL Batch No.
Kerugoya CRH | 61200
Kimbimbi | 59222
Kianyaga | 59966
Sagana | 70080
Kagumo | 71100

**Kiambu Facilities**

Kiambu CRH | 70300
Wangige | 55660
Karuri | 60600
Kigumo | 66900

-----


 Please let us know if you have any trouble or need further assistance.

Best
Lydia

**Comment by LydiaKiragu** [comment]
1. Start typing the name of facility you would like to generate reports for, and select the facility.
2. Enter the batch # as shown above correlating to the facility of interest. e.g:

![image](https://user-images.githubusercontent.com/35918052/45015649-047a3400-b02b-11e8-9a78-3af9109cb6a1.png)

3. Click on Log In. 

4. Click on the VL REPORTS tab as shown in arrow.

![image](https://user-images.githubusercontent.com/35918052/45015798-794d6e00-b02b-11e8-816d-6ff37c9901c8.png)

5. Select the period of interest as shown below. e.g. follow steps a, b1, b2 and C as shown in the pic below.

![image](https://user-images.githubusercontent.com/35918052/45015982-04c6ff00-b02c-11e8-9112-735321d28e84.png)


6. This should download an Excel file. It may / may not generate an error about the format. If you get the error complaining about the format, simply click "YES" to generate the pre-selected platform format.

![image](https://user-images.githubusercontent.com/35918052/45016270-ce3db400-b02c-11e8-9fd1-414b778f9a4b.png)

7. Repeat steps 6 to load 2 files for (b1 and b2 ) as above.  Copy paste into a single file and push results into IQ-Care or you may also choose to push results as 2 separate files. Which ever works easier for you.

**Comment by Liliankirigo96** [comment]
Well received....

Thankyou.
